CI: Bump ruby_docker to 4.18
Bump ruby_docker image to the latest image, which includes ruby 3.
The addresses QA jobs failing with:

ERROR:  Error installing gitlab-qa:
	The last version of gitlab-qa (>= 0) to support your Ruby & RubyGems was 11.3.0. Try installing it with `gem install gitlab-qa -v 11.3.0`
	gitlab-qa requires Ruby version >= 3.0.0. The current ruby version is 2.7.4.191.

Example job: https://gitlab.com/gitlab-org/cloud-native/gitlab-operator/-/jobs/4564975696

Equivalent change in Charts:
https://gitlab.com/gitlab-org/charts/gitlab/-/merge_requests/3262